name: Run Content Validation Tool
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: DotNetSdkVersion  
    value: '8.0.x' 

jobs:
  - job: ContentValidation
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: $(DotNetSdkVersion)
        installationPath: $(Agent.ToolsDirectory)/dotnet 

    - task: Bash@3
      displayName: Build All Project
      inputs:
        targetType: inline
        script: |
          dotnet build

    - task: Bash@3
      displayName: Get Test Data Source
      inputs:
        targetType: inline
        script: |
          cd DataSource
          dotnet build
          dotnet run

    - task: Bash@3
      displayName: Run Test Cases
      inputs:
        targetType: inline
        script: |
          cd ContentValidation.Test
          dotnet build
          pwsh bin/Debug/net8.0/playwright.ps1 install    
          dotnet test