name: Run Content Validation Tool
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: DotNetSdkVersion  
    value: '8.0.x' 

jobs:
  - job: RunContentValidationTestCase
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: $(DotNetSdkVersion)
        installationPath: $(Agent.ToolsDirectory)/dotnet 